[project]
name = "singleuser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kenjiro Taura", email = "tau@eidos.ic.i.u-tokyo.ac.jp" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyterhub>=6.0.1",
    "nbgrader>=0.9.6",
]

[project.scripts]
singleuser = "singleuser:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
