[all:vars]
ansible_user=azureuser
ansible_user_group=Ubuntu
# hard-code into all.yml because these vars are loaded after parsing all.yml;
# putting them here are too late
# ldap_vars_file=vars/ldap.yml
# slurm_vars_file=vars/slurm.yml
ansible_python_interpreter=/usr/bin/python3

[default]
taulec.zapto.org   hostname=taulec   ethipv4=172.16.0.4 rdmaipv4=172.16.0.4 fqdn=taulec.zapto.org   glbipv4=20.89.95.155

[nfs_server]
taulec.zapto.org

[nfs_client]

[ldap_server]
taulec.zapto.org

[ldap_client]
taulec.zapto.org

[web_server]
taulec.zapto.org

[litellm_host]
taulec.zapto.org

[open_webui_host]
taulec.zapto.org

[desktop]

[cpu]

[gpu]

[slurm_control]

[slurm_node]

[none]
