[all:vars]
ansible_user=azureuser
ansible_user_group=Ubuntu
# hard-code into all.yml because these vars are loaded after parsing all.yml;
# putting them here are too late
# ldap_vars_file=vars/ldap.yml
# slurm_vars_file=vars/slurm.yml

[default]
taulec.zapto.org   hostname=taulec   ethipv4=10.0.0.8 rdmaipv4=10.0.0.8 fqdn=taulec.zapto.org   glbipv4=130.33.37.171
#taulecx.zapto.org   hostname=taulecx   ethipv4=10.0.0.10 rdmaipv4=10.0.0.10 fqdn=taulecx.zapto.org   glbipv4=4.189.168.19

# taulecgw.zapto.org hostname=taulecgw ethipv4=10.0.0.4 rdmaipv4=10.0.0.4 fqdn=taulecgw.zapto.org glbipv4=130.33.50.36
# tauleg.zapto.org   hostname=tauleg   ethipv4= rdmaipv4= fqdn=tauleg.zapto.org   glbipv4=

[nfs_server]
#taulecgw.zapto.org
taulec.zapto.org

[nfs_client]
#taulec.zapto.org
#taulex.zapto.org

[ldap_server]
#taulecgw.zapto.org
taulec.zapto.org

[ldap_client]
#taulecgw.zapto.org
taulec.zapto.org

[web_server]
taulec.zapto.org
#taulex.zapto.org

[desktop]

[cpu]
# taulecgw.zapto.org
# taulec.zapto.org

[gpu]
# tauleg.zapto.org

[slurm_control]
# taulecgw.zapto.org

[slurm_node]
# taulec.zapto.org
# tauleg.zapto.org

[none]
